# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75f9bb1a51541ee68e1a9ec9b800d478404ccf0752ff984d2876c0c1c582c1633b59289bf5f3a8c4cf2293a084933c71009175031bd2d37ea3ffe76e4ddf821e

test:
  secret_key_base: 1a99bf3b333f25c94344a58ba8ba885fa7a8bbc51d3d864011bcd774b4c1af9070ce276ade7b68aa1a0ad8d8c9214f74c70734ebf12cb8cd11bd9b8361d29935

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
